import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    tokens: 'src/tokens/tokens.ts',
    badge: 'src/components/badge/index.ts',
    button: 'src/components/button/index.ts',
    card: 'src/components/card/index.ts',
    'check-indicator': 'src/components/check-indicator/index.ts',
    combobox: 'src/components/combobox/index.ts',
    'confirmation-modal': 'src/components/confirmation-modal/index.ts',
    'context-menu': 'src/components/context-menu/index.ts',
    'empty-state': 'src/components/empty-state/index.ts',
    'error-banner': 'src/components/error-banner/index.ts',
    'expandable-search': 'src/components/expandable-search/index.ts',
    'field-label': 'src/components/field-label/index.ts',
    'form-modal': 'src/components/form-modal/index.ts',
    'info-button': 'src/components/info-button/index.ts',
    input: 'src/components/input/index.ts',
    marquee: 'src/components/marquee/index.ts',
    menu: 'src/components/menu/index.ts',
    modal: 'src/components/modal/index.ts',
    popover: 'src/components/popover/index.ts',
    'popover-button': 'src/components/popover-button/index.ts',
    portal: 'src/components/portal/index.ts',
    'search-input': 'src/components/search-input/index.ts',
    'selection-bar': 'src/components/selection-bar/index.ts',
    spinner: 'src/components/spinner/index.ts',
    'theme-scope': 'src/components/theme-scope/index.ts',
    tooltip: 'src/components/tooltip/index.ts',
    'undo-notice': 'src/components/undo-notice/index.ts',
    'view-toggle': 'src/components/view-toggle/index.ts',
    wizard: 'src/components/wizard/index.ts',
  },
  format: ['esm'],
  dts: process.env.AS_UI_WATCH ? false : true,
  splitting: true,
  sourcemap: true,
  clean: false,
  treeshake: 'smallest',
})
